### ISSUE TITLE
Broken link for pre-trained model

### ISSUE THREAD

**Issue by raduromaniuc** [rafaelbou/-Realistic-Fingerprint-Generator#1]
Hello, Rafael

It would be extremely helpful if you could update the link for the pre-trained model, as it is now invalid

**Comment by rafaelbou** [comment]
Hi,
Sorry for the delay. I've updated the link to the pre-trained model weights.
Please try to use the new link, and let me know if you have any issues.

Thanks,
Rafael

**Comment by rafaelbou** [comment]
Link to the pre-trained model weights was updated

**Comment by nhussein** [comment]
hello, 
Could you update the link, i am not able to download the pretrained fingernet model
